services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx:tar
    depends_on:
      - wordpress
    ports:
      - target: 443
        published: 443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/run/secrets:ro
    networks:
      - inception
    restart: on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb:tar
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    networks:
      - inception
    expose:
      - 3306
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:tar
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/run/secrets:ro
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  db:
    name: db
    driver: local
  wordpress:
    name: wordpress
    driver: local

secrets:
  db_credentials:
    file: ../secrets/db_credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_credentials:   
    file: ../secrets/wp_credentials.txt
  wp_root_password:
    file: ../secrets/wp_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt  
