services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    # env_file:
    #   - .env
    # environment:
    #   - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always

  wordpress:
    container_name: wp-php
    build: ./requirements/wordpress/.
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

