services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
  #   restart: always
  #   env_file: .env
  #   networks:
  #     - my_network
  #   volumes:
  #     - mariadb_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  wordpress:
    container_name: wp-php
    build: ./requirements/wordpress/.
    volumes:
      - ./web:/var/www/html
    # restart: always
    # env_file: .env
    # depends_on:
    #   - mariadb
    # networks:
    #   - my_network
    # ports:
    #   - "9000:9000"

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    # restart: always
    # depends_on:
    #   - wordpress
    # networks:
    #   - my_network
    
    

# networks:
#   my_network:
#     driver: bridge

# volumes:
#   mariadb_data:
#     driver: local
#   wordpress_data:
#     driver: local

