services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx:tar
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - target: 443
        published: 443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb:tar
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
      - db_credentials
    environment:
      MYSQL_CREDENTIALS_FILE: /run/secrets/db_credentials
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart:
      on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:tar
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
      - wp_password
      - wp_root_password
      - wp_credentials
      - db_credentials
    environment:
      MYSQL_CREDENTIALS_FILE: /run/secrets/db_credentials
      WP_CREDENTIALS_FILE: /run/secrets/wp_credentials
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      WP_ROOT_PASSWORD_FILE: /run/secrets/wp_root_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_password
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      on-failure

networks:
  inception:
    driver: bridge

volumes:
  db:
    name: db
    driver: local
  wordpress:
    name: wordpress
    driver: local

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_root_password:
    file: ../secrets/wp_root_password.txt
  wp_credentials:
    file: ../secrets/wp_credentials.txt
  db_credentials:
    file: ../secrets/db_credentials.txt
