FROM debian:latest

# Actualizar e instalar mariadb-server
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y mariadb-server

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY init.sql /etc/mysql/init.sql

COPY script.sh .
RUN chmod +x script.sh

RUN mkdir /run/mysqld

CMD ["./script.sh"]