FROM alpine:latest

RUN apk add --no-cache mariadb mariadb-client

# Crear directorios de datos y configuración
RUN mkdir -p /run/mysqld && chown -R mysql:mysql /run/mysqld
RUN mkdir -p /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql

# Copiar archivos de configuración
COPY conf/my.cnf /etc/mysql/my.cnf
COPY tools/init_db.sh /docker-entrypoint-initdb.d/init_db.sh

# Exponer el puerto de MySQL
EXPOSE 3306

# Definir el comando de inicio
CMD ["mysqld", "--datadir=/var/lib/mysql", "--user=mysql"]