-- CREATE DATABASE IF NOT EXISTS $DB_NAME ;
-- CREATE USER IF NOT EXISTS $DB_USER@'%' IDENTIFIED BY $DB_PSW ;
-- GRANT ALL PRIVILEGES ON *.* TO $DB_USER@'%' ;
-- ALTER USER 'root'@'localhost' IDENTIFIED BY $DB_ROOT_PSW ;

CREATE DATABASE wordpress;
CREATE USER 'wpuser'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'wpuser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;