# Imagen base de NGINX
FROM nginx:alpine

# Instalamos la instalación de paquetes de Alpine. No instala Nginx porque ya está incluido en la imagen nginx:alpine.
RUN apk --no-cache add openssl

# Copiamos el archivo de configuración de NGINX
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

# Copiamos certificados TLS
COPY ./certs/ /etc/ssl/certs/

# Exponemos el puerto 443 para HTTPS
EXPOSE 443

# El contenedor permanecerá activo mientras Nginx esté funcionando.
ENTRYPOINT ["nginx", "-g", "daemon off;"]
