# Imagen base de NGINX
FROM nginx:alpine

# Instalamos la instalación de paquetes de Alpine. No instala Nginx porque ya está incluido en la imagen nginx:alpine.
RUN apk --no-cache add openssl

# Copiamos el archivo de configuración de NGINX
RUN mkdir /etc/nginx/conf
COPY ./conf/nginx.conf /etc/nginx/conf/nginx.conf

# Copia el script de generación del certificado
COPY ./conf/generate_cert.sh /usr/local/bin/generate_cert.sh
RUN chmod +x /usr/local/bin/generate_cert.sh

# El contenedor permanecerá activo mientras Nginx esté funcionando.
ENTRYPOINT ["nginx", "-g", "daemon off;"]
